spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/restaurant
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

upload:
  path: C:\Users\Ilya\Desktop\course\restaurant-automation\src\main\resources\static\img



  session:
    timeout: 1999999m
    store-type : redis

security:
  ignored: /**